# Generated by Django 4.0.4 on 2022-05-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_follow'),
        ),
        migrations.AddConstraint(
            model_name='readed',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_readed'),
        ),
    ]
