# Generated by Django 3.2.13 on 2022-05-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Пользователь подписан на блог', 'verbose_name_plural': 'Пользователи подписаны на блоги'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='readed',
            options={'verbose_name': 'Прочитанный пост', 'verbose_name_plural': 'Прочитанные посты'},
        ),
    ]
