# Generated by Django 4.0.4 on 2022-05-17 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_v1', '0002_follow_unique_follow_readed_unique_readed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readed',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='readed_post', to='api_v1.post'),
        ),
        migrations.AlterField(
            model_name='readed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_readed_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
